### ISSUE TITLE
Raspi ADC/IMU blocks

### ISSUE THREAD

**Issue by josujugo** [robertobucher/pysimCoder#1]
Dear Roberto:

I have been testing the new code for raspberry pi crosscompiling with pysimcoder. Great work. I am wondering if the spi devices to connect with the ADC/IMU blocks are particular ones or the code is generic and must be tuned depending on the selected chip.

Thanks

**Comment by robertobucher** [comment]
Sorry Josu for the very later answer, but I only found now your question.

The two functions are quite specific for the tho kind of HW

**Comment by josujugo** [comment]
Don't worry, Roberto, I appreciate very much your work and that you share it with all us.

Could you say me the details of such HW? Just in case we use hardware in the classes (We usually use only software simulations).

**Comment by robertobucher** [comment]
Hi Josu

In the last time a was working on an interesting improvement of the pysimCoder application, in order to obtain code for the NuttX RTOS.
NuttX offers a Posix layer that can be used for about 500 different embedded systems: this means that the same SW can run on about 500 uControllers! More info at https://nuttx.apache.org

I did some tests using a STM32F446 and a STM32F746nucleo board, using ADC, PWM, DI, DO, CAN.

**Comment by josujugo** [comment]
Hi, Roberto:

Thanks you for your hint. I will soon working again with pysimCoder since I use it in a Master Course and I will study the new development. I don’t know the  NuttX RTOS, but sounds very interesting with support for so many board.

Your work is very valuable,

Thanks a lot!

josu
